import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useState} from "react";
import {Fade} from 'react-awesome-reveal';
import Game from "../src/components/game";
import Menu from "../src/components/menu";

function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Motle!</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Motle!
                </h1>

                <p className={styles.description}>
                    A mutilanguage Wordle game.
                </p>

                <Menu languages={"a"}></Menu>

                <Fade>

                </Fade>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
                </a>
            </footer>
        </div>
    )
}

export default Home
